import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

import '../../core/app_colors.dart';
import '../../core/farmer_theme.dart';
import '../../services/farmer_controller.dart';
import '../../widgets/farmer/farmer_card.dart';
import '../../widgets/farmer/farmer_section_title.dart';
import '../../widgets/farmer/farmer_shared.dart';

class FarmerPlanPage extends StatefulWidget {
  const FarmerPlanPage({
    super.key,
    required this.farmer,
    required this.onViewHistory,
  });

  final FarmerController farmer;
  final VoidCallback onViewHistory;

  @override
  State<FarmerPlanPage> createState() => _FarmerPlanPageState();
}

class _FarmerPlanPageState extends State<FarmerPlanPage> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) widget.farmer.refresh(force: true);
    });
  }

  @override
  Widget build(BuildContext context) {
    return ListenableBuilder(
      listenable: widget.farmer,
      builder: (context, _) {
        final f = widget.farmer;
        final latest = f.latestEvaluation;

        return ColoredBox(
          color: FarmerTheme.surface,
          child: RefreshIndicator(
            onRefresh: () => f.refresh(force: true),
            color: AppColors.primary,
            child: CustomScrollView(
              slivers: [
                SliverToBoxAdapter(
                  child: Padding(
                    padding: const EdgeInsets.fromLTRB(16, 16, 16, 0),
                    child: FarmerCard(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const FarmerSectionTitle(title: 'Crops & fertilizer plan'),
                          const SizedBox(height: 8),
                          Text(
                            'This plan is generated by the administrator from your farm assessment and saved automatically to your account.',
                            style: TextStyle(color: Colors.grey.shade700, height: 1.45),
                          ),
                          const SizedBox(height: 16),
                          if (f.loading && latest == null)
                            const Center(
                              child: Padding(
                                padding: EdgeInsets.symmetric(vertical: 12),
                                child: CircularProgressIndicator(color: AppColors.primary),
                              ),
                            )
                          else if (f.error != null && latest == null)
                            Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(f.error!, style: const TextStyle(color: AppColors.errorText)),
                                const SizedBox(height: 12),
                                OutlinedButton(
                                  onPressed: () => f.refresh(force: true),
                                  child: const Text('Retry'),
                                ),
                              ],
                            )
                          else if (latest == null)
                            Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const Text(
                                  'No admin-generated plan is available yet. Please wait for approval or refresh.',
                                  style: TextStyle(color: AppColors.textSecondary, height: 1.5),
                                ),
                                const SizedBox(height: 12),
                                OutlinedButton.icon(
                                  onPressed: () => f.refresh(force: true),
                                  icon: const Icon(Icons.refresh_rounded),
                                  label: const Text('Refresh'),
                                ),
                              ],
                            )
                          else ...[
                            Container(
                              width: double.infinity,
                              padding: const EdgeInsets.all(16),
                              decoration: BoxDecoration(
                                gradient: LinearGradient(
                                  colors: [AppColors.primaryDark, AppColors.primary],
                                ),
                                borderRadius: BorderRadius.circular(18),
                              ),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    latest.topCrop.toUpperCase(),
                                    style: const TextStyle(
                                      color: Colors.white,
                                      fontSize: 26,
                                      fontWeight: FontWeight.w800,
                                    ),
                                  ),
                                  const SizedBox(height: 6),
                                  Text(
                                    '${(latest.topConfidence * 100).toStringAsFixed(1)}% suitability · soil health ${latest.soilHealthScore.toStringAsFixed(0)}',
                                    style: TextStyle(color: Colors.white.withValues(alpha: 0.9), fontSize: 13),
                                  ),
                                  const SizedBox(height: 6),
                                  Text(
                                    'Generated ${DateFormat.yMMMd().add_jm().format(latest.createdAt)}',
                                    style: TextStyle(color: Colors.white.withValues(alpha: 0.82), fontSize: 12),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(height: 14),
                            OutlinedButton.icon(
                              onPressed: () => showFarmerEvaluationDetail(
                                context,
                                api: widget.farmer.api,
                                predictionId: latest.id,
                              ),
                              icon: const Icon(Icons.visibility_outlined),
                              label: const Text('View full plan'),
                            ),
                            const SizedBox(height: 10),
                            TextButton.icon(
                              onPressed: widget.onViewHistory,
                              icon: const Icon(Icons.history_rounded),
                              label: const Text('See all saved plans'),
                            ),
                          ],
                        ],
                      ),
                    ),
                  ),
                ),
                const SliverToBoxAdapter(child: SizedBox(height: 24)),
                if (latest != null)
                  SliverPadding(
                    padding: const EdgeInsets.fromLTRB(16, 0, 16, 24),
                    sliver: SliverToBoxAdapter(
                      child: FarmerCard(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            const FarmerSectionTitle(title: 'Latest saved evaluation'),
                            const SizedBox(height: 8),
                            Text(
                              '${latest.topCrop.toUpperCase()} · ${DateFormat.yMMMd().format(latest.createdAt)}',
                              style: const TextStyle(fontWeight: FontWeight.w800),
                            ),
                            const SizedBox(height: 6),
                            Text(
                              'The plan above was created by the admin approval flow and stored in your profile history.',
                              style: TextStyle(color: Colors.grey.shade700, height: 1.45),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
              ],
            ),
          ),
        );
      },
    );
  }
}